# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 16:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('primary_key', models.CharField(default=users.models.pkgen, max_length=10, primary_key=True, serialize=False)),
                ('activation_key', models.CharField(default='0', max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.datetime(2016, 5, 20, 16, 36, 57, 287928))),
                ('braintree_merchant_id', models.CharField(max_length=200)),
                ('braintree_customer_id', models.CharField(max_length=200)),
                ('picture', models.FileField(upload_to='uploads/')),
                ('school', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('graduation_year', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', localflavor.us.models.USStateField()),
                ('zip', models.IntegerField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
