# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='braintree_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='braintree_merchant_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='sd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 15, 6, 37, 526699)),
        ),
    ]
