# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160525_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 14, 49, 25, 38300)),
        ),
    ]
