# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160530_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='listed_first_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 15, 53, 44, 298166)),
        ),
    ]
