# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160604_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 6, 0, 18, 11, 398432)),
        ),
    ]
