# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 16:38
from __future__ import unicode_literals

import checkout.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date', models.DateTimeField(default=datetime.datetime(2016, 5, 20, 16, 38, 40, 442188))),
                ('primary_key', models.CharField(default=checkout.models.pkgen, max_length=10, primary_key=True, serialize=False)),
                ('payment', models.CharField(max_length=200)),
                ('confirmed', models.BooleanField(default=False)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_total', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.IntegerField(choices=[(1, 'On Campus'), (2, 'Off Campus'), (3, 'Both')])),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_item_total_price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('seller_confirmed', models.BooleanField(default=False)),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('braintree_id_transaction', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='checkout.Order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
