# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20160524_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 15, 6, 37, 533958)),
        ),
    ]
