# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20160525_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='braintree_id_transaction',
            new_name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 14, 49, 25, 42267)),
        ),
    ]
