# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20160529_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 15, 41, 30, 220238)),
        ),
    ]
