# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20160529_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 3, 1, 53, 703219)),
        ),
    ]
