# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20160530_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 4, 19, 32, 50, 425675)),
        ),
    ]
