# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 00:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20160605_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 6, 0, 18, 11, 405683)),
        ),
    ]
