# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 03:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20160606_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 3, 21, 33, 15438)),
        ),
    ]
