# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_auto_20160608_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 19, 19, 19, 941619)),
        ),
    ]
