# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.CharField(default='test_sub', max_length=200),
            preserve_default=False,
        ),
    ]
