# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160530_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stripe_listing_fee_id',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.Category'),
        ),
    ]
